<h2>Ingreso de Usuario</h2>
<div class="form-container">
        <form action="login" method="POST">
            <label for="email">Correo Electrónico:</label>
            <input type="text" id="email" name="email" required>

            <label for="contraseña">Contraseña:</label>
            <input type="password" id="contraseña" name="contraseña" required>
            <label for="rol">Ingrese su rol:</label>
            <input type="text" id="rol" name="rol" required>

            <input type="submit" value="Ingresar">
        </form>
    </div>