
<h2>Ingreso de Usuario</h2>
<div class="form-container">
        <form action="login" method="POST">
            <label for="email">Correo Electrónico:</label>
            <input type="text" id="email" name="email" required>

            <label for="contraseña">Contraseña:</label>
            <input type="password" id="contraseña" name="contraseña" required>
            <label for="rol">Ingrese su rol:</label>
            <input type="text" id="rol" name="rol" required>

            <input type="submit" value="Ingresar">
        </form>
        <a href="logout">Cerrar Sesión</a>
    </div>
    <h2>Solo los Administradores puede acceder a estos links</h2>
    <div class="link-container">
    <a href="FormularioAgregar">Link para agregar en la tabla</a>
    <a href="formularioEliminar">Link para borrar elementos de la tabla</a>
    <a href="formularioEditar">Link para editar elementos de la tabla</a>
</div>